[versions]
minecraft = "1.21.3"
yarn = "1.21.3+build.2"
fabric-loader = "0.16.9"
kotlin = "2.0.21"
loom = "1.8-SNAPSHOT"
coroutines = "1.9.0"
koin = "4.0.0"
serialization = "1.7.3"
collections-immutable = "0.3.8"
minotaur = "2.+"

# Minecraft Mods
fabric-api = "0.108.0+1.21.3"
fabric-language-kotlin = "1.12.3+kotlin.2.0.21"
modmenu = "12.0.0"
yacl = "3.6.2+1.21.2-fabric"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collections-immutable" }
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }

# Minecraft Mods
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
yacl = { group = "dev.isxander", name = "yet-another-config-lib", version.ref = "yacl" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
modrinth-minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }